#ifndef _CUSTOM_SETTING_H_
#define _CUSTOM_SETTING_H_

#undef INFLUXDB_CLIENT_TESTING_SERVER_HOST
#undef INFLUXDB_CLIENT_TESTING_SSID
#undef INFLUXDB_CLIENT_TESTING_PASS

#define INFLUXDB_CLIENT_TESTING_SERVER_HOST "192.168.88.73"
#define INFLUXDB_CLIENT_TESTING_SSID "Bonitoo-ng"
#define INFLUXDB_CLIENT_TESTING_PASS "change1t"


#endif //_CUSTOM_SETTING_H_